# Generated by Django 4.2.7 on 2024-01-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notification_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
