# Generated by Django 4.2.7 on 2024-01-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='notification_id',
        ),
    ]
