# Generated by Django 4.2.7 on 2024-01-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='notification_id',
        ),
    ]
