# Generated by Django 4.2.7 on 2024-01-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20240125_1545'),
        ('posts', '0009_remove_comment_notification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_in_feed',
            field=models.BooleanField(default=False),
        ),
    ]
