# Generated by Django 4.2.7 on 2024-01-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_profile_chat_status'),
        ('posts', '0010_post_profile_post_show_in_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts', to='accounts.profile'),
        ),
    ]
