# Generated by Django 4.2.7 on 2023-12-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='searchers.terms'),
        ),
    ]
