# Generated by Django 4.2.7 on 2023-11-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_friendship'),
        ('accounts', '0004_profile_avatar'),
    ]

    operations = [
    ]
