# Generated by Django 4.2.7 on 2023-11-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_0004_friendship_0004_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
