# Generated by Django 4.2.7 on 2023-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_age_profile_gender_profile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
    ]
