# Generated by Django 4.2.7 on 2023-12-26 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_invisible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_online',
        ),
        migrations.CreateModel(
            name='UserLastOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_online', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
