# Generated by Django 4.2.7 on 2024-01-18 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_last_online_delete_userlastonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(1955, 2, 24, 0, 0)),
        ),
    ]
