# Generated by Django 4.2.7 on 2024-01-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_age'),
        ('accounts', '0015_customuser_country'),
    ]

    operations = [
    ]
