# Generated by Django 4.2.7 on 2024-01-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_0012_remove_profile_age_0015_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
