# Generated by Django 4.2.7 on 2024-01-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_age_visible_profile_bio_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate_visible',
            field=models.BooleanField(default=True),
        ),
    ]
