# Generated by Django 4.2.7 on 2024-01-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_avatar'),
        ('accounts', '0019_profile_birthdate_visible'),
    ]

    operations = [
    ]
