# Generated by Django 4.2.7 on 2024-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20240125_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_status',
            field=models.BooleanField(default=False),
        ),
    ]
