# Generated by Django 4.2.7 on 2024-01-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_chat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chat_status',
        ),
    ]
