# Generated by Django 4.2.7 on 2024-01-04 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
