# Generated by Django 4.2.7 on 2024-01-04 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_room_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
